blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="blog"),
    path("article/<int:pk>", BlogDetailView.as_view(), name="article"),
    path("new_article", BlogCreateView.as_view(), name="new_article"),
    path("edit_article/<int:pk>", BlogUpdateView.as_view(), name="edit_article"),
    path("delete_article/<int:pk>", BlogDeleteView.as_view(), name="delete_article"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {"null": True, "blank": True}


class Article(models.Model):
    title = models.CharField(max_length=225, verbose_name="заголовок")
    description = models.TextField(verbose_name="описание")
    content = models.TextField(verbose_name="содержание")
    is_published = models.BooleanField(verbose_name="Опубликовано", default=False)
    preview_img = models.ImageField(
        upload_to="article_images", verbose_name="Изображение", **NULLABLE
    )
    created_at = models.DateField(
        verbose_name="Дата создания", auto_now=True, **NULLABLE
    )
    updated_at = models.DateField(
        verbose_name="Дата изменения", auto_now=True, **NULLABLE
    )
    view_count = models.IntegerField(verbose_name="Количество просмотров", default=0)
    slug = models.CharField(max_length=255, unique=True, **NULLABLE)

    class Meta:
        verbose_name = "статья"
        verbose_name_plural = "статьи"
        ordering = ("title",)
        permissions = [
            (
                "can_change_article_is_published",
                "Может редактировать статус публикации",
            ),
            ("can_change_article_description", "Может редактировать описание"),
            ("can_change_article_content", "Может редактировать контент"),
            ("can_change_article_preview_img", "Может редактировать изображение"),
            ("can_change_article_slug", "Может редактировать slug"),
            ("can_delete_article_article", "Может удалять статью"),
            ("can_create_article_article", "Может создавать статью"),
        ]

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from blog.models import Article


class FormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            print(field_name)
            if field_name == "is_active":
                field.widget.attrs["class"] = "form-check-input"


class ContentManagerForm(FormMixin, forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "description", "content", "preview_img"]


class ModeratorForm(FormMixin, forms.ModelForm):
    class Meta:
        model = Article
        fields = ["is_published"]

blog/views.py
from blog.models import Article
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy
from django.utils.text import slugify
from blog.forms import ContentManagerForm, ModeratorForm


class BlogListView(ListView):
    model = Article
    template_name = "blog/blog.html"

    def queryset(self):
        return Article.objects.filter(is_published=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Мой блог"
        return context


class BlogDetailView(DetailView):
    model = Article
    template_name = "blog/article.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.object.title
        return context

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    model = Article
    template_name = "blog/new_article.html"
    fields = ["title", "description", "content", "preview_img", "is_published"]
    success_url = reverse_lazy("blog:blog")

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Article
    template_name = "blog/edit_article.html"

    def get_form_class(self):
        if self.request.user.groups.filter(name="ContentManager").exists():
            return ContentManagerForm
        else:
            return ModeratorForm

    def get_success_url(self):
        return reverse_lazy("blog:article", args=[self.object.pk])


class BlogDeleteView(DeleteView):
    model = Article
    template_name = "blog/confirm.html"
    success_url = reverse_lazy("blog:blog")

blog/templates/blog/article.html
{% extends "catalog/base.html" %}
{% block content %}
{% load my_tags %}
{% load static %}
<div class="container col-xxl-8 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
      <div class="col-10 col-sm-8 col-lg-6">
      <img src="{{ object.preview_img | media }}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
      </div>
      <div class="col-lg-6">
        <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">{{ object.name }}</h1>
        <h3 class="lead">{{ object.author }}</h3>
        <div class="d-flex align-items-center">
          <small class="text-body-secondary ml-2">{{ object.view_count }} 👁️ Просмотров</small>
        </div>
        <p class="lead">{{ object.content | text }}</p> 
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/blog/blog.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container px-4 py-5" id="custom-cards">
<h2 class="pb-2 border-bottom">Мой блог</h2>
{% if user.is_authenticated %}
<a class="btn btn-primary" href="{% url 'blog:new_article' %}">Новая статья</a>
{% endif %}
<div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
{% for article in object_list %}
<div class="col">
  <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-color: rgba(33, 37, 41, 0.78) !important;">
    <div class="card-bg" style="background-image: url({{ article.preview_img | media }});"></div>
    <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
           <a href="{% url 'blog:article' article.pk  %}" style="text-decoration: none; color: white;">
          <h5 class="pt-5 mt-5 mb-4 display-7 lh-1 fw-bold">{{ article.title }}</h5>
          <p class="pt-5 mt-2 mb-3 display-6 lh-1" style="font-size: smaller; color: rgba(255, 255, 255, 0.5)">{{ article.description | truncatechars:100 }}</p>

      </a>
      <ul class="d-flex list-unstyled mt-auto justify-content-between">
        <li class="d-flex align-items-center me-3">
          <small class="sr-only">Опубликовано: {{ article.created_at }}</small>
        </li>
        <li class="d-flex align-items-center">
          <small>{{ article.view_count }} 👁️</small>
        </li>
      </ul>
   <div class="btn-group" role="group" aria-label="Basic mixed styles example">
    <a href="{% url 'blog:article' article.pk  %}" class="btn btn-outline-light" style="background-color: rgba(33, 37, 41, 0.78) !important;">Читать</a>
    {% if user|is_in_group:"ContentManager" %}
    <a href="{% url 'blog:edit_article' article.pk  %}" class="btn btn-outline-light" style="background-color: rgba(33, 37, 41, 0.78) !important;">Редактировать</a>
    <a href="{% url 'blog:delete_article' article.pk  %}" class="btn btn-outline-light" style="background-color: rgba(33, 37, 41, 0.78) !important;">Удалить</a>
    {% endif %}
    {% if user|is_in_group:"Moderator" %}
    <a href="{% url 'blog:edit_article' article.pk  %}" class="btn btn-outline-light" style="background-color: rgba(33, 37, 41, 0.78) !important;">Снять с публикации</a>
    {% endif %}
   </div>
    </div>
  </div>
</div>     
{% endfor %} 
  </div>
</div>


{% endblock %}

blog/templates/blog/confirm.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-md-7 py-4">
<h1>Удалить статью?</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Удалить">
  <a href="{% url 'blog:blog' %}" class="btn btn-outline-secondary">Отмена</a>
</form>
    </div>
</div>
</div>
{% endblock %}

blog/templates/blog/edit_article.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-md-7 py-4">
<h1>Добавить статью</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Сохранить">
</form>
    </div>
</div>
</div>
{% endblock %}

blog/templates/blog/new_article.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-md-7 py-4">
<h1>Добавить статью</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Сохранить">
</form>
    </div>
</div>
</div>
{% endblock %}