blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="blog"),
    path("article/<int:pk>", BlogDetailView.as_view(), name="article"),
    path("new_article", BlogCreateView.as_view(), name="new_article"),
    path("edit_article/<int:pk>", BlogUpdateView.as_view(), name="edit_article"),
    path("delete_article/<int:pk>", BlogDeleteView.as_view(), name="delete_article"),
]

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import (
    index,
    CatalogListView,
    CatalogDetailView,
    CatalogCreateView,
    ContactsView,
    CatalogUpdateView,
    category_list_view
)
from  django.views.decorators.cache import cache_page

app_name = CatalogConfig.name

urlpatterns = [
    path("", index, name="index"),
    path("catalog", CatalogListView.as_view(), name="catalog"),
    path("contacts", ContactsView.as_view(), name="contacts"),
    path("product_item/<int:pk>", cache_page(600)(CatalogDetailView.as_view()), name="product_item"),
    path("new_product", CatalogCreateView.as_view(), name="new_product"),
    path("update_product/<int:pk>", CatalogUpdateView.as_view(), name="update_product"),
    path("categories/", category_list_view, name='category_list' )]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetDoneView,
    PasswordResetView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
)
from users.apps import UsersConfig
from users.views import (
    RegisterView,
    ProfileView,
    LoginUserView,
    email_verification,
)

from django.urls import reverse_lazy

app_name = UsersConfig.name


urlpatterns = [
    path("", LoginUserView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path(
        "profile/",
        ProfileView.as_view(template_name="users/profile.html"),
        name="profile",
    ),
    path("activate/<str:token>/", email_verification, name="email_verification"),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
]

catalog/models.py
from django.db import models

NULLABLE = {"null": True, "blank": True}


class Products(models.Model):
    product_name = models.CharField(max_length=225, verbose_name="продукт")
    description = models.TextField(verbose_name="описание")
    preview_img = models.ImageField(
        upload_to="product_images", verbose_name="Изображение", **NULLABLE
    )
    category = models.ForeignKey(
        "Category", on_delete=models.CASCADE, verbose_name="категория"
    )
    price = models.IntegerField(verbose_name="Цена")
    created_at = models.DateField(
        verbose_name="Дата создания", auto_now=True, **NULLABLE
    )
    updated_at = models.DateField(
        verbose_name="Дата изменения", auto_now=True, **NULLABLE
    )
    # manufactured_at = models.DateField(verbose_name='Дата производства', **NULLABLE)
    view_count = models.IntegerField(verbose_name="Количество просмотров", default=0)
    slug = models.SlugField(max_length=255, unique=True, **NULLABLE)
    user = models.ForeignKey(
        "users.User",
        on_delete=models.DO_NOTHING,
        verbose_name="пользователь",
        **NULLABLE,
        related_name="products",
    )
    is_published = models.BooleanField(verbose_name="Опубликовано", default=False)

    def __str__(self):
        return f"{self.product_name}"

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        ordering = ("product_name",)
        permissions = [
            ("can_change_is_published", "Может редактировать статус публикации"),
            (
                "can_change_product_description",
                "Может редактировать количество описание",
            ),
            ("can_change_product_category", "Может редактировать категорию"),
        ]


class Category(models.Model):
    category_name = models.CharField(max_length=225, verbose_name="категория")
    description = models.TextField(verbose_name="описание")
    has_products = models.BooleanField(verbose_name="Есть продукты")

    def __str__(self):
        return f"{self.category_name}"

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ("category_name",)


class Version(models.Model):
    product = models.ForeignKey(
        Products,
        on_delete=models.CASCADE,
        verbose_name="продукт",
        **NULLABLE,
        related_name="versions",
    )
    version = models.IntegerField(verbose_name="номер версии")
    name_version = models.CharField(
        verbose_name="имя версии", **NULLABLE, max_length=225
    )
    created_at = models.DateField(
        verbose_name="дата создания", auto_now=True, **NULLABLE
    )
    is_active = models.BooleanField(verbose_name="Активна", default=False)

    def __str__(self):
        return f"{self.version}"

    class Meta:
        verbose_name = "версия"
        verbose_name_plural = "версии"
        ordering = ("version",)

catalog/forms.py
from django import forms
from catalog.models import Products, Version
from django.core.exceptions import ValidationError

STOP_WORDS = [
    "казино",
    "криптовалюта",
    "крипта",
    "биржа",
    "дешево",
    "бесплатно",
    "обман",
    "полиция",
    "радар",
]


class FormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            print(field_name)
            if field_name == "is_active":
                field.widget.attrs["class"] = "form-check-input"

    def clean_product_name(self):
        cleaned_data = super().clean()["product_name"]

        if cleaned_data in STOP_WORDS:
            raise ValidationError("Недопустимое имя продукта")
        else:
            return cleaned_data


class CatalogCreateForm(FormMixin, forms.ModelForm):
    class Meta:
        model = Products
        fields = (
            "product_name",
            "description",
            "preview_img",
            "category",
            "price",
            "is_published",
        )


class CatalogUpdateForm(FormMixin, forms.ModelForm):
    class Meta:
        model = Products
        fields = ("product_name", "description", "preview_img", "category", "price")


class ModeratorUpdateForm(FormMixin, forms.ModelForm):
    class Meta:
        model = Products
        fields = (
            "is_published",
            "description",
            "category",
        )


class VersionForm(FormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = ("version", "name_version", "is_active")

catalog/views.py
from django.shortcuts import render
from catalog.models import Category, Products, Version
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
)
from django.urls import reverse_lazy
from catalog.forms import (
    CatalogCreateForm,
    VersionForm,
    CatalogUpdateForm,
    ModeratorUpdateForm,
)
from django.forms import inlineformset_factory
from django.contrib.auth.mixins import LoginRequiredMixin
from config.cached import get_cached


def index(request):
    context = {
        "top": Products.objects.all().order_by("-view_count")[:3],
        "title": "Главная",
    }
    return render(request, "index.html", context)


class CatalogListView(ListView):
    model = Products
    template_name = "catalog.html"
    context_object_name = "products"

    def get_queryset(self):
        # Получаем все продукты, у которых есть активные версии
        return Products.objects.prefetch_related("versions").all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Получаем активные версии для всех продуктов
        active_versions = Version.objects.filter(is_active=True)

        # Создаем словарь для хранения активных версий по продуктам
        version_dict = {}
        for version in active_versions:
            version_dict[version.product.id] = version.version

        # Добавляем номер версии в контекст для каждого продукта
        for product in context["products"]:
            product.current_version = version_dict.get(product.id)

        context["title"] = "Каталог"
        return context


class CatalogDetailView(DetailView):
    model = Products
    template_name = "product_item.html"
    context_object_name = "product"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.object.product_name
        return context

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.view_count += 1
        obj.save()
        return obj


class CatalogFormMixin:
    template_name = "new_product.html"

    def get_success_url(self):
        return reverse_lazy("catalog:catalog")


class CatalogCreateView(CatalogFormMixin, CreateView, LoginRequiredMixin):
    model = Products
    form_class = CatalogCreateForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ProductFormset = inlineformset_factory(
            Products, Version, form=VersionForm, extra=1
        )
        if self.request.method == "POST":
            context_data["formset"] = ProductFormset(
                self.request.POST, instance=self.object
            )
        else:
            context_data["formset"] = ProductFormset(instance=self.object)

        context_data["title"] = "Новый продукт"
        return context_data

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.user = user
        product.save()

        context_data = self.get_context_data()
        formset = context_data["formset"]
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(
                self.get_context_data(form=form, formset=formset)
            )


class CatalogUpdateView(CatalogFormMixin, UpdateView):
    model = Products

    def get_form_class(self):
        if self.request.user.groups.filter(name="Moderator").exists():
            return ModeratorUpdateForm
        else:
            return CatalogUpdateForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ProductFormset = inlineformset_factory(
            Products, Version, form=VersionForm, extra=0
        )
        if self.request.method == "POST":
            context_data["formset"] = ProductFormset(
                self.request.POST, instance=self.object
            )
        else:
            context_data["formset"] = ProductFormset(instance=self.object)

        context_data["title"] = "Изменение продукта"
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data["formset"]
        self.object = form.save()
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(
                self.get_context_data(form=form, formset=formset)
            )


class ContactsView(TemplateView):
    template_name = "contacts.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Контакты"
        return context


def category_list_view(request):
    categories = get_cached(Category, 600)

    return render(request, "categories.html", {"categories": categories})

catalog/templates/catalog/includes/card.html
{% load my_tags %}
{% load static %}
<div class="card mb-3">
  <div class="card-title, text-center">
     <h5 class="card-title">{{ product.product_name }}</h5>
     <small class="text-muted">Версия продукта - {{ product.current_version }}</small>
     <small class="text-muted">Продавец - {{ product.user.first_name | no_name }}</small>
    </div>
  <img src="{{ product.preview_img | media }}" class="card-img-top" alt="Изображение">
  <div class="card-body">
         <h6 class="card-subtitle mb-2 text-muted">{{ product.price }} RUB</h6>
        <p class="card-text">{{ product.description | truncatechars:30 }}</p>
          <a href="{% url 'catalog:product_item' product.pk  %}" class="btn btn-primary">Подробнее</a>
          {% if product.user == user or perms.catalog.can_change_is_published %}
          <a href="{% url 'catalog:update_product' product.pk  %}" class="btn btn-success">Изменить</a>
          {% endif %}
            </div>
</div>

catalog/templates/catalog/includes/custom_cards.html
{% load static %}
{% load my_tags %}
<div class="container px-4 py-5" id="custom-cards">
    <h2 class="pb-2 border-bottom">Популярные товары</h2>

    <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
{% for product in top %}
<div class="col">
  <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-color: rgba(33, 37, 41, 0.78) !important;">
    <div class="card-bg" style="background-image: url({{ product.preview_img | media }});"></div>
    <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
      <a href="{% url 'catalog:product_item' product.pk  %}" style="text-decoration: none;">
      <h5 class="pt-5 mt-5 mb-4 display-7 lh-1 fw-bold">{{ product.product_name }}</h5>
      </a>
      <ul class="d-flex list-unstyled mt-auto justify-content-between">
        <li class="d-flex align-items-center me-3">
          <small class="sr-only">{{ product.price }} руб.</small>
        </li>
        <li class="d-flex align-items-center">
          <small>{{ product.view_count }} 👁️</small>
        </li>
      </ul>
    </div>
  </div>
</div>     
{% endfor %}
      
    </div>
  </div>

catalog/templates/catalog/includes/footer.html
 <div class="bg-light mt-5">
        <div class="container py-5">
            <div class="row">
                <div class="col-md-6">
                    <div id="map">
                        <script type="text/javascript" charset="utf-8" async
                            src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Af7902ddd498fb9e9a29e002c74f4a29bdb5ff2f6c51239be226a30d64dcd7b16&amp;width=523&amp;height=414&amp;lang=ru_RU&amp;scroll=true"></script>
                    </div>
                </div>
                <div class="col-md-6">
                    <h5>Напишите нам.</h5>
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="name">Ваше имя</label>
                            <input type="text" class="form-control" name="name">
                        </div>
                        <div class="form-group">
                            <label for="email">Ваш email</label>
                            <input type="email" class="form-control" name="email">
                        </div>
                        <div class="form-group">
                            <label for="message">Ваше сообщение</label>
                            <textarea class="form-control" name="message" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

catalog/templates/catalog/includes/header.html
{% load static %}
{% load my_tags %}
<div class="navbar navbar-expand-lg navbar-light bg-light">
   <a class="navbar-brand" href="{% url 'catalog:index' %}">Гильдия Глиномесов</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'catalog:catalog' %}">Каталог</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'blog:blog' %}">Блог</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'catalog:category_list' %}">Категории</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/contacts">Контакты</a>
                </li>
                <li class="nav-item active">
                  {% if user.is_authenticated %}
                  {% if perms.catalog.add_product %}
                    <a class="nav-link btn btn-primary btn-lg px-4 me-md-2" href="{% url 'catalog:new_product' %}">Новый продукт</a>
                  {% endif %}
                  {% endif %}
                </li>
            </ul>
        </div>
      <div class="row">
        <div class="button-container" style="display: flex;">
          {% if user.is_authenticated %}
          <a class="navbar-brand" style="font-size: 16px;" href="{% url 'users:profile' %}">
         <img src="{{ user.avatar | no_avatar }}" width="30" height="30" class="d-inline-block align-top rounded-circle" alt="avatar">
              {{ user.first_name | no_name }}
          </a>
            <form method="post" action="{% url 'users:logout' %}" style="margin-right: 10px;"> 
          {% csrf_token %}
            <button class="btn btn-outline-primary" type="submit">Выйти</button>
            </form>
          {% if user.is_authenticated %}
            <form method="post" action="{% url 'users:profile' %}" >
          {% csrf_token %}
            <button class="btn btn-outline-success" href="{% url 'users:profile' %}" type="submit">Профиль</button>
            </form>
          {% endif %}
        </div>
          {% else %}
        <div class="button-container" style="display: flex;">
            <a class="btn btn-outline-primary" href="{% url 'users:login' %}" style="margin-right: 10px;">Войти</a>
            <a class="btn btn-outline-danger" href="{% url 'users:register' %}">Регистрация</a>
            {% endif %}
        </div>
      </div>
  </div>

catalog/templates/catalog/includes/hero.html
{% load static %}
<div class="container col-xxl-10 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
      <div class="col-10 col-sm-8 col-lg-6">
      <img src="{% static 'img/gon4ar.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Изображение гончара." width="700" height="500" loading="lazy">
      </div>
      <div class="col-lg-6">
        <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">Производим по старинным технологиям.</h1>
        <p class="lead">Гончарная мастерская - это место, где рождаются удивительные произведения искусства из глины. Здесь творчество сочетается с мастерством, а руки гончара оживают и создают уникальные предметы.</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a href="{% url 'catalog:catalog' %}"><button type="button" class="btn btn-primary btn-lg px-4 me-md-2">Каталог</button></a>
        </div>
      </div>
    </div>
  </div>