blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="blog"),
    path("article/<int:pk>", BlogDetailView.as_view(), name="article"),
    path("new_article", BlogCreateView.as_view(), name="new_article"),
    path("edit_article/<int:pk>", BlogUpdateView.as_view(), name="edit_article"),
    path("delete_article/<int:pk>", BlogDeleteView.as_view(), name="delete_article"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetDoneView,
    PasswordResetView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
)
from users.apps import UsersConfig
from users.views import (
    RegisterView,
    ProfileView,
    LoginUserView,
    email_verification,
)

from django.urls import reverse_lazy

app_name = UsersConfig.name


urlpatterns = [
    path("", LoginUserView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path(
        "profile/",
        ProfileView.as_view(template_name="users/profile.html"),
        name="profile",
    ),
    path("activate/<str:token>/", email_verification, name="email_verification"),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
]

users/models.py
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)
from django.db import models


NULLABLE = {"null": True, "blank": True}


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("Поле Email должно быть установлено")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, verbose_name="email")
    phone = models.CharField(max_length=20, verbose_name="телефон", **NULLABLE)
    avatar = models.ImageField(upload_to="users/", verbose_name="аватар", **NULLABLE)
    country = models.CharField(max_length=100, verbose_name="страна", **NULLABLE)

    first_name = models.CharField(max_length=100, verbose_name="имя", **NULLABLE)
    last_name = models.CharField(max_length=100, verbose_name="фамилия", **NULLABLE)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    token = models.CharField(max_length=100, verbose_name="токен", **NULLABLE)
    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"

users/forms.py
# pyright:reportIncompatibleVarggVableOverride=false

from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    AuthenticationForm,
)
from django.contrib.auth.views import PasswordResetForm
from users.models import User


class FormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class UserRegisterForm(FormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ["email", "password1", "password2"]


class UserProfileForm(FormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "phone", "avatar"]


class UserLoginForm(FormMixin, AuthenticationForm):
    class Meta:
        model = User
        fields = [
            "email",
            "password",
        ]

users/views.py
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.views import LoginView
from users.forms import (
    UserRegisterForm,
    UserProfileForm,
    UserLoginForm,
)
from users.models import User
from django.urls import reverse, reverse_lazy

from django.core.mail import send_mail
from config.settings import EMAIL_HOST_USER
import secrets
from django.shortcuts import get_object_or_404, redirect


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        host = self.request.get_host()
        url = f"http://{host}/users/activate/{token}"
        user.token = token
        user.save()
        send_mail(
            subject="Подтверждение регистрации",
            message=f"Для подтверждения регистрации перейдите по ссылке: {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )

        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = "users/profile.html"
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user


class LoginUserView(LoginView):
    form_class = UserLoginForm
    template_name = "users/login.html"
    success_url = reverse_lazy("users:login")

users/templates/users/login.html
{% extends "catalog/base.html" %}

{% block content %}
<form class="row" method="post">
    {% csrf_token %}
    <div class="col-md-3">
        {{ form.as_p }}
        <button class="btn btn-success">войти</button>
        <a class="btn btn-danger" href="{% url 'users:password_reset' %}">Воcстановить пароль</a>
    </div>
</form>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "catalog/base.html" %}

{% block content %}
<h2>Пароль изменен</h2>
<p>Вы успешно сменили пароль. Используйте новый пароль для входа</p>
<p><a href="{% url 'users:login' %}">Войти</a></p>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "catalog/base.html" %}

{% block content %}
<h2>Новый пароль</h2>
<form method="post">
    {% csrf_token %}
  <div class="form-error">{{ form.non_field_errors }}</div>
  {% for f in form %}
  <p>
    <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
    {{ f }}
  </p>
  <div class="form-error">{{ f.errors }}</div>
  {% endfor %}
    <button class="btn btn-success">Сохранить</button>
    </form>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "catalog/base.html" %}

{% block content %}
<h2>Восстановление пароля</h2>
<p>На ваш почтовый адрес отправлено письмо с инструкциями по восстановлению пароля.</p>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends "catalog/base.html" %}

{% block content %}
<h2>Восстановление пароля</h2>
<form method="post">
    {% csrf_token %}
    {% for f in form %}
    <p>
      <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
      {{ f }}
    </p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
      <button class="btn btn-success">Восстановить</button>
    </div>
</form>
{% endblock %}

users/templates/users/profile.html
{% extends "catalog/base.html" %}
<div class="col-md-6">
{% block content %}
<form class="row basic-form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="col-md-3">
        {{ form.as_p }}
        <button class="btn btn-success">Сохранить изменения</button>
    </div>
</form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends "catalog/base.html" %}

{% block content %}
<form class="row" method="post">
    {% csrf_token %}
    <div class="col-md-3">
        {{ form.as_p }}
        <button class="btn btn-success">Зарегистрироваться</button>
    </div>
</form>
{% endblock %}